### ISSUE TITLE
Fail to reproduce README example

### ISSUE THREAD

**Issue by JunyiLiu2002** [MagliaLab/HoleyPy#15]
Hi,

I'm trying to reproduce the example in the README file. However, when I'm executing the last two code blocks (i.e. Events.run() & Features.run()), it throws an error:
TypeError                                 Traceback (most recent call last)
~\HoleyPy-v1.0.0\MagliaLab-HoleyPy-b6af35b\test.ipynb Cell 7 in <cell line: 2>()
      [1](line=0) # If levels were not set manually, this will use Levels(signal_data) to determine them.
----> [2](line=1) level_0, level_1, level_0_start, level_0_end, level_1_start, level_1_end = Events(signal_data).run()

TypeError: cannot unpack non-iterable bool object

It seems that the run() function is returning a bool value (self.result), instead of the desired values. I'm wondering how to fix this, or to do something else to get the values out. Thanks in advance!

**Comment by flrlucas** [comment]
I reproduced the error, indeed the class returns a bool currently, we will update this.

Events (and features) can be extracted more efficiently as following:
`events = Events(signal_data)`
`events.run()`
`events.events` List of named tuples: baseline_start, baseline_end, event_start, and event_end. All in datapoints
`events.features` List of named tuple: baseline_current, baseline_sd, event_current, event_sd, residual_current, residual_current_sd, dwell_time

Keep in mind that the events and features lists now are named tuple rather than regular lists.
You can access the data using e.g. `events.features[0].baseline_current`

**Comment by JunyiLiu2002** [comment]
Hi, 
Thanks a lot for your reply.

But I found that this method does not work for the last step:
 'excluded_current, excluded_current_variance, dwell_time = Features(signal_data).run()'
because the features.run() can not work properly and also return the error  'cannot unpack non-iterable bool object'

I'm wondering how to fix this, or to do something else to get the values out. Thanks in advance!

**Comment by flrlucas** [comment]
The default operation has changed from a two step operation to a single.
`Features(signal).run()` is run internally and the results can be accessed by default after detecting events.
Thus, you don't need to run `Features(signal).run()`. I shall push an update for the readme.

Example:
`events = Events(signal_data)`
`events.run()`
`events.features` <- List of named tuple: baseline_current, baseline_sd, event_current, event_sd, residual_current, residual_current_sd, dwell_time

Additonally, you may wonder about the excluded/residual current.
- The excluded current is the complementary to one of the residual current. 
- Use of either is purely semantic, if not sure, use residual current:
- - When describing the current gave events, use residual current
- - When describing a physical blockage gave the events, use excluded current

**Comment by JunyiLiu2002** [comment]
The result I want to get from the last step is the excluded current and hope to see how it can be calculated from the updated readme. Thanks!

**Comment by flrlucas** [comment]
The readme on the devel (default) branch has been updated.
If any further issues arise, please let us know
